language: cpp
sudo: required
dist: trusty

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libusb-1.0
      - inotify-tools
      - libboost-dev
      
script:
  - (cd CPU/CPUsoftware/lib && make)
  - (cd CPU/CPUsoftware && make)